(cl:defpackage consert-msg
  (:use )
  (:export
   "<CONTEXTANNOTATION>"
   "CONTEXTANNOTATION"
   "<NARYASSERTION>"
   "NARYASSERTION"
   "<ENTITYROLE>"
   "ENTITYROLE"
   "<UNARYASSERTION>"
   "UNARYASSERTION"
   "<CONTEXTASSERTION>"
   "CONTEXTASSERTION"
   "<BINARYASSERTION>"
   "BINARYASSERTION"
   "<CONTEXTENTITY>"
   "CONTEXTENTITY"
   "<ENTITYDESCRIPTION>"
   "ENTITYDESCRIPTION"
  ))

