package org.aimas.consert

// Declare Metadata for CASAS events
import org.aimas.consert.tests.casas.assertions.Item
import org.aimas.consert.tests.casas.assertions.Cabinet
import org.aimas.consert.tests.casas.assertions.Phone
import org.aimas.consert.tests.casas.assertions.PersonLocation

import org.aimas.consert.model.annotations.AnnotationData
import org.aimas.consert.model.annotations.DefaultAnnotationData
import org.aimas.consert.model.annotations.AnnotationUtils

import org.aimas.consert.tests.casas.assertions.PhoneCall

import java.util.Date;

import org.aimas.consert.engine.EventTracker

global EventTracker eventTracker;

/*
rule "Using Phone Book"
	when
	    $loc: PersonLocation(location == "DiningTable") from entry-point "ExtendedPersonLocationStream"
	    $item: Item(sensorId == "I08", status == "ABSENT", this annHappensBefore[0s, 10s] $loc) from "ExtendedItemStream"
	then
	    System.out.println("////// Triggering USING PHONE BOOK following events: " + $loc + " AND " + $item + "\n");
	    
	    UsingPhoneBook phoneBook = new UsingPhoneBook();
	    eventTracker.insertStaticEvent(phoneBook);
end
*/

rule "Phone Call Start"
	when
	    $phone: Phone(value == "START") from entry-point "ExtendedPhoneStream"
	    $loc: PersonLocation(location == "DiningTable", this annIntersects $phone) from entry-point "ExtendedPersonLocationStream"
	then
	    System.out.println("////// Triggering PHONE CALL START following events: " + $loc + " AND " + $phone + "\n");
	    
	    DefaultAnnotationData locAnn = (DefaultAnnotationData)$loc.getAnnotations();
	    long ts = drools.getWorkingMemory().getSessionClock().getCurrentTime();
	    DefaultAnnotationData ann = new DefaultAnnotationData(ts, locAnn.getConfidence(), locAnn.getStartTime(), new Date(ts));
	    
	    PhoneCall phoneCall = new PhoneCall(ann);
	    eventTracker.insertDerivedEvent(phoneCall);
end

rule "Phone Call Ongoing"
	when
	    $phone: Phone(value == "START") from entry-point "ExtendedPhoneStream"
	    $loc: PersonLocation(location == "DiningTable", locAnn : annotations, this annIntersects $phone) from entry-point "ExtendedPersonLocationStream"
	    $call: PhoneCall(callAnn : annotations, this annIntersects $loc) from entry-point "ExtendedPhoneCallStream"
	    
	then
	    System.out.println("////// Triggering PHONE CALL ONGOING following events: " + $loc + " AND " + $call + " AND " + $phone + "\n");
	    
	    AnnotationData ann = callAnn.applyCombinationOperator(locAnn);
	    PhoneCall phoneCall = new PhoneCall(ann);
	    
	    eventTracker.insertDerivedEvent(phoneCall);
end