package org.aimas.consert

// Declare Metadata for CASAS events
import org.aimas.consert.tests.casas.assertions.Motion
import org.aimas.consert.tests.casas.assertions.Item
import org.aimas.consert.tests.casas.assertions.Cabinet
import org.aimas.consert.tests.casas.assertions.Water
import org.aimas.consert.tests.casas.assertions.Temperature
import org.aimas.consert.tests.casas.assertions.Burner
import org.aimas.consert.tests.casas.assertions.Phone
import org.aimas.consert.tests.casas.assertions.PersonLocation
import org.aimas.consert.tests.casas.assertions.HandlingFood
import org.aimas.consert.tests.casas.assertions.HeatingFood
import org.aimas.consert.tests.casas.assertions.PhoneCall
import org.aimas.consert.tests.casas.assertions.ProbablyCleaning

import org.aimas.consert.model.annotations.AnnotationData
import org.aimas.consert.model.annotations.DefaultAnnotationData
import org.aimas.consert.model.annotations.AnnotationUtils

import org.aimas.consert.engine.EventTracker

global EventTracker eventTracker;

declare Motion
    @role(event)
    //@expires(1m)
    //@timestamp(startTimestamp)
    //@duration(eventDuration)
end


declare Item
    @role(event)
    //@expires(10m)
    //@timestamp(startTimestamp)
    //@duration(eventDuration)
end


declare Cabinet
    @role(event)
    //@expires(10m)
    //@timestamp(startTimestamp)
    //@duration(eventDuration)
end

declare Water
    @role(event)
    //@expires(10m)
    //@timestamp(startTimestamp)
    //@duration(eventDuration)
end


declare Temperature
    @role(event)
    //@expires(10s)
    //@timestamp(startTimestamp)
    //@duration(eventDuration)
end

declare Burner
    @role(event)
    //@expires(10m)
    //@timestamp(startTimestamp)
    //@duration(eventDuration)
end

declare Phone
    @role(event)
    //@expires(10m)
    //@timestamp(startTimestamp)
    //@duration(eventDuration)
end

declare HandlingFood
    @role(event)
end

declare HeatingFood
    @role(event)
end


// =========== BaseEvent insert rules - needed to crea      te the event streams
/*
rule "MotionInsertTest"
    when
        $motion : Motion(id : sensorId, status : status) from entry-point "MotionStream" 
    then
        System.out.println("Inserted MOTION event with sensorId: " + id + ", status: " + status + ", timestamp: " + (long)$motion.getStartTimestamp());
end
*/

rule "ItemInsertTest"
    salience(-10)
    when
        $item : Item(id : sensorId, status : status) from entry-point "ItemStream" 
    then
        System.out.println("Inserted ITEM event with sensorId: " + id + ", status: " + status + ", timestamp: " + (long)$item.getStartTimestamp());
        //long ts = drools.getWorkingMemory().getSessionClock().getCurrentTime();
        //DefaultAnnotationData ann = new DefaultAnnotationData(ts);
        //Item item = new Item(id, status, ann);
        // eventTracker.insertAtomicEvent(item);
end

rule "CabinetInsertTest"
    when
        $cabinet : Cabinet(id : sensorId, status : status) from entry-point "CabinetStream" 
    then
        System.out.println("Inserted CABINET event with sensorId: " + id + ", status: " + status + ", timestamp: " + (long)$cabinet.getStartTimestamp());
end

rule "WaterInsertTest"
    when
        $water : Water(id : sensorId, val : value) from entry-point "WaterStream" 
    then
        System.out.println("Inserted WATER event with sensorId: " + id + ", value: " + val + ", timestamp: " + (long)$water.getStartTimestamp());
end

rule "TemperatureInsertTest"
    when
        $temp : Temperature(id : sensorId, val : value) from entry-point "TemperatureStream" 
    then
        System.out.println("Inserted TEMPERATURE event with sensorId: " + id + ", value: " + val + ", timestamp: " + (long)$temp.getStartTimestamp());
end

rule "BurnerInsertTest"
    when
        $burner : Burner(val : value) from entry-point "BurnerStream" 
    then
        System.out.println("Inserted BURNER event with value: " + val + ", timestamp: " + (long)$burner.getStartTimestamp());
end


rule "PhoneInsertTest"
    when
        $phone : Phone(val : status) from entry-point "PhoneStream" 
    then
        System.out.println("Inserted PHONE event with value: " + val + ", timestamp: " + (long)$phone.getStartTimestamp());
end


rule "PersonLocationTest"
    salience -10
    when
        $loc : PersonLocation(location : location) from entry-point "PersonLocationStream" 
    then
        System.out.println("Inserted PersonLocation event with location: " + location + ", timestamp: " + (long)$loc.getStartTimestamp() + 
        " duration: " + (long)$loc.getEventDuration());
end

rule "PersonLocationExtended"
    salience -10
    when
        $loc : PersonLocation(location : location) from entry-point "ExtendedPersonLocationStream" 
    then
        System.out.println("Inserted EXTENDED PersonLocation event with location: " + location + ", timestamp: " + (long)$loc.getStartTimestamp() + 
        " duration: " + (long)$loc.getEventDuration());
end


rule "HandlingFoodTest"
    salience -10
    when
        $food : HandlingFood() from entry-point "HandlingFoodStream" 
    then
        System.out.println("Inserted HandlingFood event with: " + $food + ", timestamp: " + (long)$food.getStartTimestamp() + 
        " duration: " + (long)$food.getEventDuration());
end

rule "ExtendedHandlingFood"
    salience -10
    when
        $food : HandlingFood() from entry-point "ExtendedHandlingFoodStream" 
    then
        System.out.println("Inserted EXTENDED HandlingFood event with: " + $food + ", timestamp: " + (long)$food.getStartTimestamp() + 
        " duration: " + (long)$food.getEventDuration());
end


rule "HeatingFoodTest"
    salience -10
    when
        $food : HeatingFood() from entry-point "HeatingFoodStream" 
    then
        System.out.println("Inserted HeatingFood event with: " + $food + ", timestamp: " + (long)$food.getStartTimestamp() + 
        " duration: " + (long)$food.getEventDuration());
end


rule "ExtendedHeatingFoodTest"
    salience -10
    when
        $food : HeatingFood() from entry-point "ExtendedHeatingFoodStream" 
    then
        System.out.println("Inserted ExtendedHeatingFood event with: " + $food + ", timestamp: " + (long)$food.getStartTimestamp() + 
        " duration: " + (long)$food.getEventDuration());
end

rule "PhoneCallTest"
    salience -10
    when
        $phone : PhoneCall() from entry-point "PhoneCallStream" 
    then
        System.out.println("Inserted PhoneCall event with: " + $phone + ", timestamp: " + (long)$phone.getStartTimestamp() + 
        " duration: " + (long)$phone.getEventDuration());
end


rule "ProbablyCleaningTest"
    salience -10
    when
        $probCleaning : ProbablyCleaning() from entry-point "ProbablyCleaningStream" 
    then
        System.out.println("Inserted ProbablyCleaning event with: " + $probCleaning + ", timestamp: " + (long)$probCleaning.getStartTimestamp() + 
        " duration: " + (long)$probCleaning.getEventDuration());
end