package org.aimas.consert

// Declare Metadata for CASAS events
import org.aimas.consert.tests.casas.assertions.Item
import org.aimas.consert.tests.casas.assertions.Cabinet
import org.aimas.consert.tests.casas.assertions.Phone
import org.aimas.consert.tests.casas.assertions.PersonLocation

import org.aimas.consert.model.annotations.AnnotationData
import org.aimas.consert.model.annotations.DefaultAnnotationData
import org.aimas.consert.model.annotations.AnnotationUtils

import org.aimas.consert.tests.casas.assertions.PhoneCall

import java.util.Date;

import org.aimas.consert.engine.EventTracker

global EventTracker eventTracker;


declare PhoneCall
    @role(event)
end

/*
rule "Using Phone Book"
	when
	    $loc: PersonLocation(location == "DiningTable") from entry-point "ExtendedPersonLocationStream"
	    $item: Item(sensorId == "I08", status == "ABSENT", this annHappensBefore[0s, 10s] $loc) from "ExtendedItemStream"
	then
	    System.out.println("////// Triggering USING PHONE BOOK following events: " + $loc + " AND " + $item + "\n");
	    
	    UsingPhoneBook phoneBook = new UsingPhoneBook();
	    eventTracker.insertStaticEvent(phoneBook);
end
*/

rule "Phone Call"
	when
	    $phone: Phone(status == "START", phoneAnn : annotations#DefaultAnnotationData) from entry-point "PhoneStream"
	    not (Phone(this after $phone) from entry-point "PhoneStream")
	    $loc: PersonLocation(location == "DiningTable", locAnn : annotations#DefaultAnnotationData, this annIntersects $phone) from entry-point "ExtendedPersonLocationStream"
	then
	    System.out.println("////// Triggering PHONE CALL following events: " + $loc + " AND " + $phone + "\n");
	    
	    long ts = drools.getWorkingMemory().getSessionClock().getCurrentTime();
	    DefaultAnnotationData ann = new DefaultAnnotationData(ts, locAnn.getConfidence(), phoneAnn.getStartTime(), new Date(ts));
	    
	    PhoneCall phoneCall = new PhoneCall(ann);
	    eventTracker.insertDerivedEvent(phoneCall);
end

/*
rule "Phone Call Ongoing"
	when
	    $phone: Phone(value == "START") from entry-point "PhoneStream"
	    not (Phone(this after $phone) from entry-point "PhoneStream")
	    $loc: PersonLocation(location == "DiningTable", locAnn : annotations, this annIncludes $phone) from entry-point "ExtendedPersonLocationStream"
	    exists PhoneCall(callAnn : annotations, this annIntersects $loc) from entry-point "ExtendedPhoneCallStream"
	then
	    System.out.println("////// Triggering PHONE CALL ONGOING following events: " + $loc + " AND " + $phone + "\n");
	    
	    AnnotationData ann = callAnn.applyCombinationOperator(locAnn);
	    PhoneCall phoneCall = new PhoneCall(ann);
	    
	    eventTracker.insertDerivedEvent(phoneCall);
end
*/