package org.aimas.consert

// Declare the metadata for the `Position` and `LLA` events
import org.aimas.consert.eventmodel.Position
import org.aimas.consert.eventmodel.SittingLLA
import org.aimas.consert.eventmodel.WalkingLLA
import org.aimas.consert.eventmodel.StandingLLA

import org.aimas.consert.eventmodel.WorkingHLA
import org.aimas.consert.eventmodel.DiscussingHLA
import org.aimas.consert.eventmodel.ExerciseHLA

import org.aimas.consert.eventmodel.AnnotationInfo
import org.aimas.consert.eventmodel.AnnotationUtils
import org.aimas.consert.eventmodel.ValidityInterval

// ============ declaring Position metadata
declare Position
    @role(event)
    @timestamp(startTimestamp)
    @duration(eventDuration)
end

// ============ declaring LLA metadata
declare SittingLLA
    @role(event)
    @timestamp(startTimestamp)
    @duration(eventDuration)
end

declare WalkingLLA
    @role(event)
    @timestamp(startTimestamp)
    @duration(eventDuration)
end

declare StandingLLA
    @role(event)
    @timestamp(startTimestamp)
    @duration(eventDuration)
end

// =========== declaring HLA metadata
declare WorkingHLA
    @role(event)
    @timestamp(startTimestamp)
    @duration(eventDuration)
end

declare DiscussingHLA
    @role(event)
    @timestamp(startTimestamp)
    @duration(eventDuration)
end

declare ExerciseHLA
    @role(event)
    @timestamp(startTimestamp)
    @duration(eventDuration)
end


// =========== BaseEvent test rules

rule "PositionInsertTest"
    when
        $pos : Position(p : person, t : type) from entry-point "PositionStream" 
    then
        System.out.println("Inserted POS event with person: " + p.getName() + ", type: " + t + ", timestamp: " + (long)$pos.getStartTimestamp() + ", duration: " + $pos.getEventDuration());
end


rule "SittingLLAInsertTest"
    when
        $lla : SittingLLA(p : person, t : type) from entry-point "LLAStream"
    then
        System.out.println("Inserted LLA event with person: " + p.getName() + ", type: " + t + ", timestamp: " + (long)$lla.getStartTimestamp() + ", duration: " + $lla.getEventDuration());
end

rule "WalkingLLAInsertTest"
    when
        $lla : WalkingLLA(p : person, t : type) from entry-point "LLAStream"
    then
        System.out.println("Inserted LLA event with person: " + p.getName() + ", type: " + t + ", timestamp: " + (long)$lla.getStartTimestamp() + ", duration: " + $lla.getEventDuration());
end

rule "StandingLLAInsertTest"
    when
        $lla : StandingLLA(p : person, t : type) from entry-point "LLAStream"
    then
        System.out.println("Inserted LLA event with person: " + p.getName() + ", type: " + t + ", timestamp: " + (long)$lla.getStartTimestamp() + ", duration: " + $lla.getEventDuration());
end

rule "ExtendedPositionInsertTest"
    when
        $pos : Position(p : person, t : type) from entry-point "ExtendedPositionStream" 
    then
        System.out.println("Inserted EXTENDED POS event with person: " + p.getName() + ", type: " + t + ", lastUpdated: " + (long)$pos.getAnnotations().getLastUpdated() + 
            ", from: " + $pos.getAnnotations().getStartTime().getTimeInMillis() + ", to: " + $pos.getAnnotations().getEndTime().getTimeInMillis());
end

rule "ExtendedSittingLLAInsertTest"
    when
        $lla : SittingLLA(p : person, t : type) from entry-point "ExtendedLLAStream"
    then
        System.out.println("Inserted EXTENDED LLA event with person: " + p.getName() + ", type: " + t + ", lastUpdated: " + (long)$lla.getAnnotations().getLastUpdated() + 
            ", from: " + $lla.getAnnotations().getStartTime().getTimeInMillis() + ", to: " + $lla.getAnnotations().getEndTime().getTimeInMillis());
end


rule "ExtendedWalkingLLAInsertTest"
    when
        $lla : WalkingLLA(p : person, t : type) from entry-point "ExtendedLLAStream"
    then
        System.out.println("Inserted EXTENDED LLA event with person: " + p.getName() + ", type: " + t + ", lastUpdated: " + (long)$lla.getAnnotations().getLastUpdated() + 
            ", from: " + $lla.getAnnotations().getStartTime().getTimeInMillis() + ", to: " + $lla.getAnnotations().getEndTime().getTimeInMillis());
end


rule "ExtendedStandingLLAInsertTest"
    when
        $lla : StandingLLA(p : person, t : type) from entry-point "ExtendedLLAStream"
    then
        System.out.println("Inserted EXTENDED LLA event with person: " + p.getName() + ", type: " + t + ", lastUpdated: " + (long)$lla.getAnnotations().getLastUpdated() + 
            ", from: " + $lla.getAnnotations().getStartTime().getTimeInMillis() + ", to: " + $lla.getAnnotations().getEndTime().getTimeInMillis());
end

// =========== HLA detection rules

/*
rule "WorkingHLA"
  agenda-group "HLA"
  when
    $pos : Position($p : person, type == "WORK_AREA", $annPos : annotations) from entry-point "ExtendedPositionStream"
    $lla : SittingLLA(person == $p, $annLLA : annotations) from entry-point "ExtendedLLAStream"
    
    AnnotationUtils.intersects($pos.getAnnotations().getStartTime(), $pos.getAnnotations().getEndTime(), 
        $lla.getAnnotations().getStartTime(), $lla.getAnnotations().getEndTime())
  then
    // create WorkingHLA
    double hlaTs = AnnotationUtils.maxTimestamp($pos.getAnnotations().getTimestamp(), $lla.getAnnotations().getTimestamp());
    double hlaConfidence = AnnotationUtils.maxConfidence($pos.getAnnotations().getConfidence(), $lla.getAnnotations().getConfidence());
    ValidityInterval hlaInterval = AnnotationUtils.computeIntersection(
        $pos.getAnnotations().getStartTime(), 
        $pos.getAnnotations().getEndTime(),
        $lla.getAnnotations().getStartTime(), 
        $lla.getAnnotations().getEndTime());
    
    
    AnnotationInfo ann = new AnnotationInfo(hlaTs, hlaConfidence, hlaInterval.getStart(), hlaInterval.getEnd());
    WorkingHLA hla = new WorkingHLA($p, ann);
    
    entryPoints["ExtendedWorkingHLA"].insert(hla);
end

rule "DiscussingHLA"
  agenda-group "HLA"
  when
    $pos : Position($p : person, type == "CONFERENCE_AREA")
    $lla : StandingLLA(person == $p)
    //$pos includes $lla || $lla includes $pos || $pos overlaps $lla || $lla overlaps $pos
  then
    //AnnotationInfo ann = new AnnotationInfo();
    DiscussingHLA hla = new DiscussingHLA();
    insert(hla);
end
*/