# A representation of a Context from the CONSERT context model

# The URI ID of this EntityDescription instance
string id

# The class type of this EntityDescription instance (e.g. includes - one room includes another, hasAge)
string type

# The subject ContextEntity instance of this EntityDescription
ContextEntity subject

# The object ContextEntity instance of this EntityDescription
ContextEntity object