# A representation of a n-ary ContextAssertion from the CONSERT context model

# The URI ID of this n-ary ContextAssertion instance
string id

# The class type of this n-ary ContextEntity instance
string type

# The acquisition type of the ContextAssertion
string acquisitionType

# The key-value dictionary of entities and their roles in this ContextAssertion instance
EntityRole[] entities 

# The annotations of this ContextAssertion instance
ContextAnnotation[] annotations

