package org.aimas.consert

// Declare the metadata for the `Position` and `LLA` events
import org.aimas.consert.tests.hla.assertions.Position

import org.aimas.consert.model.annotations.AnnotationData
import org.aimas.consert.model.annotations.DefaultAnnotationData
import org.aimas.consert.model.annotations.AnnotationUtils

import org.aimas.consert.engine.EventTracker

// ============ Declare Position metadata
declare Position
    @role(event)
    @timestamp(startTimestamp)
    @duration(eventDuration)
end

global java.util.List results;
global EventTracker eventTracker;

rule "PositionInsertTest"
    when
        $pos : Position(p : person, t : type) from entry-point "PositionStream"
    then
        System.out.println("Inserted TEST POS event with person: " + p.getName() + ", type: " + t + ", timestamp: " +
            (long)$pos.getStartTimestamp() + ", duration: " + $pos.getEventDuration());
end

rule "ExtendedPositionInsertTest"
    when
        $pos : Position(p : person, t : type) from entry-point "ExtendedPositionStream"
    then
     DefaultAnnotationData ann = (DefaultAnnotationData)$pos.getAnnotations();
        System.out.println("Inserted EXTENDED POS event with person: " + p.getName() + ", type: " + t +
            ", lastUpdated: " + ann.getLastUpdated() + ", from: " );
end

rule "ExtendedPositionAccumulateTest" salience 100
    when
        $numEvents : Long() from accumulate (
            $pos : Position($p : person, type == "WORK_AREA") over window:time( 10s ) from entry-point "ExtendedPositionStream",
            //$pos : Position($p : person, type == "WORK_AREA") over window:time( 10s ) from entry-point "PositionStream",
            count($pos) 
        ); 
    then
        results.add($numEvents);
        
        //System.out.println("Inserted EXTENDED POS event with person: " + p.getName() + ", type: " + t +
        //    ", lastUpdated: " + (long)$pos.getAnnotations().getLastUpdated() + ", from: " +
        //    $pos.getAnnotations().getStartTime().getTimeInMillis() + ", to: " +
        //    $pos.getAnnotations().getEndTime().getTimeInMillis());
        
end